project:
  type: book

book:
  title: ""        # Suppress default title
  author: ""       # Suppress default author
  date: ""         # Suppress default date

  # Don't include index.qmd here
  chapters:
    - intro.qmd
    - index.qmd
    - ai_definition.qmd
    - ai_models.qmd
    - ai_tools.qmd
    - applications.qmd
    - ai_in_agriculture.qmd
    - ai_power_generation.qmd
    - ai_transmission.qmd
    - ai_distribution.qmd
    - ai_industry.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    number-sections: true
    link-citations: true
    # Custom cover page explicitly set as the homepage
    include-before-body: index.qmd

  pdf:
    include-in-header: title_page.tex
    number-sections: true
    toc: true

bibliography: references.bib
csl: ieee.csl

publish:
  method: gh-pages
